name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      id: build
      run: |
        IMAGE_TAG=$(git rev-parse --short HEAD)
        docker build -t your-docker-registry/wisecow:$IMAGE_TAG .
        docker push your-docker-registry/wisecow:$IMAGE_TAG
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: '1.24.0'

    - name: Deploy to Kubernetes
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
        IMAGE_TAG: ${{ env.IMAGE_TAG }}
      run: |
        kubectl set image deployment/wisecow-deployment wisecow=your-docker-registry/wisecow:${IMAGE_TAG}
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/ingress.yaml
